services:

  mariadb:
    build:
      context: ./requirements/mariadb
    image: mariadb
    container_name: mariadb
    volumes:
      - volume_mariadb:/var/lib/mysql
    restart: on-failure
    networks:
      - inception
    environment:
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - WP_DBNAME=${MYSQL_DATABASE}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    

  wordpress:
    build:
      context: ./requirements/wordpress
    image: wordpress
    container_name: wordpress
    volumes:
      - volume_wordpress:/var/www/wordpress
    restart: on-failure
    networks:
      - inception
    environment:
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - WP_ADMIN_EMAIL=${WP_ADMIN_EMAIL}
      - WP_TITLE=${WP_TITLE}
      - WP_URL=${WP_URL}
      - DOMAIN_NAME=${DOMAIN_NAME}
    depends_on:
      - mariadb
    restart: on-failure
  
  nginx:
    build:
      context: ./requirements/nginx
    image: nginx
    container_name: nginx
    depends_on:
      - wordpress
    volumes:
      - volume_wordpress:/var/www/wordpress
    networks:
      - inception
    ports:
      - "443:443"
    restart: on-failure

volumes:
  volume_mariadb:
    driver: local
    driver_opts:
      type: none
      device: /home/dasanter/data/mariadb
      #allow to add an existent folder
      o: bind

volume_wordpress:
  driver: local
  driver_opts:
    type: none
    device: /home/dasanter/data/wordpress
    o: bind

networks:
    inception:
      driver: bridge