version : '3'

services:
  mysql:
    build:
      context: ./requirements/mariadb
    container_name: "mysql"
    volumes:
      - volume_mariadb:/var/lib/mysql
    networks:
      - inception_network
    env_file:
      - .env
    ports:
      - "3306:3306"
    restart: always

  wordpress:
    build:
      context: ./requirements/wordpress
    depends_on:
      - mysql
    volumes:
      - volume_wordpress:/var/www/html
    networks:
      - inception_network
    working_dir: /var/www/html
    ports:
      - "9000:9000"
    env_file:
      - .env
    restart: always

  nginx:
    build:
      context: ./requirements/nginx
    depends_on:
      - wordpress
    volumes:
      - volume_wordpress:/var/www/html
    networks:
      - inception_network
    ports:
      - "443:443"
    restart: always

networks:
  inception_network:
    driver: bridge
volumes:
  volume_mariadb:
    driver: local
    driver_opts:
      type: none
      device: /Users/seiseo/data/mariadb
      #allow to add an existent folder
      o: bind
  volume_wordpress:
    driver: local
    driver_opts:
      type: none
      device: /Users/seiseo/data/wordpress
      o: bind